### ISSUE TITLE
Possible semantic breakage in 0.2.11

### ISSUE THREAD

**Issue by ef4** [broccolijs/broccoli-funnel#51]
broccoli-funnel 0.2.11 breaks ember's build, because this conditional is failing to match:

https://github.com/emberjs/emberjs-build/blob/06d8c86fdd41d03c345ed7c1f166313d3c7b6fd9/lib/get-es6-package.js#L86

Funnel is passing us `ember/main.js` instead of `main.js`.

**Comment by stefanpenner** [comment]
fixed in emberjs-build, which worked around this bug.

**Comment by rwjblue** [comment]
@stefanpenner - I don't see that the new behavior is a bugfix. I agree with the initial report of this issue, it is a breaking change...

The change in funnel causes the destdir to be processed before `getDestinationPath` is called.  The prior ordering was intentional (that the `getDestionationPath` was called with the non-moved input path)...

**Comment by rwjblue** [comment]
0.2.12 uses `path.join(this.destDir, relativePath)` as the argument to `lookupDestinationPath` (see [here](https://github.com/broccolijs/broccoli-funnel/blob/v0.2.12/index.js#L196)), whereas in 0.2.7 the path provided was `relativePath` (see [here](https://github.com/broccolijs/broccoli-funnel/blob/v0.2.7/index.js#L151).  This will cause an issue for anyone using `getDestinationPath` along with `destDir`.

**Comment by stefanpenner** [comment]
@rwjblue ya that sounds like bug.

**Comment by stefanpenner** [comment]
@rwjblue if you can provide a failing test that illustrates your specific scenario that would be handy.
